# Generated by Django 4.1.13 on 2024-03-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('qualification', models.TextField(max_length=300)),
                ('contact_info', models.TextField(max_length=300)),
            ],
        ),
    ]
